@api = http://localhost:4000/products

### GET ALL
GET {{api}}
### GET BY ID
GET {{api}}/1
### ADD
POST {{api}}
Content-Type: application/json

{
    "name":"Headphones",
    "description":"extra quality sound headset",
    "quantity":58
}
### DELETE
DELETE {{api}}/8

### UPDATE
PUT {{api}}/1
Content-Type: application/json

{
    "name":"Laptop",
    "description":"HP Zbook",
    "quantity":25
}